import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"



import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/shared/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={` antialiased`}>
          <Header />
          <main className="min-h-screen">{children} <Toaster richColors/></main>
          <footer className="bg-blue-400/40 text-white text-center py-4">
            <div>
              <p className="text-black">Made With ❤️ </p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
